config/routes.rb
DuelAllDay::Application.routes.draw do
  
  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Use a secure password
  has_secure_password
  
  # Basic validations
  validates :username,:email, presence: true
  validates :username, length: { in: 4..10 }
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 4 }, on: :create
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_signin!
  
  def index    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only:[
    :edit,
    :update
  ]
  
  def edit    
  end
  
  def update
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    if @user.update(new_params)
      redirect_to admin_root_path, notice: "Your account was successfully updated."
    else
      flash[:alert] = "Account not updated."
      render :edit
    end
  end
  
  
  private 
  
  def set_user
    @user = User.friendly.find(current_user.id)
  end
  
  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  # require sign in
  def require_signin!
    if current_user.nil?
      redirect_to signin_url, alert: "You need to sign in first"
    end
  end
  helper_method :require_signin!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user ? true : false
  end
  helper_method :user_signed_in?

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def create
    @messages = Message.create!(params[:message])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to(root_path, notice: "You are already signed in.") if current_user 
  end
  
  def create
    user = User.where(username: params[:signin][:username].strip).first

    if user && user.authenticate(params[:signin][:password])
    
      session[:user_id] = user.id 
      redirect_to admin_root_path, notice: "Signed in successfully."
    else
      flash[:error] = "Wrong username/password."
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out."
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | DuelAllDay"      
    end
  end
end

app/views/admin/base/index.html.erb
<h1>Admin Zone <small>logged in as <%= current_user.username %></small></h1>

<p><%= link_to "Edit your account", edit_admin_user_path(current_user) %></p>
  

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Edit your account</h1>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_for [:admin, @user], role: "form" do |f| %>
  
    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">    
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
  
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update your account", class: "btn btn-primary" %> - <%= link_to "cancel", admin_root_path %>
      </div>
    </div>
  
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav> -->

<nav class="horizontal-nav full-width horizontalNav-notprocessed">
    <ul class="sf-menu">
           <%= render 'layouts/navigation_links' %>
         </ul>
      </nav>

app/views/layouts/_navigation_links.html.erb
<% if !current_user %>
<li><%= link_to "Sign in", signin_path %></li>
<% else %>
<li><%= link_to "Admin", admin_root_path %></li>
<li><%= link_to "Sign out", signout_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
     <head>
     <title>Duel All Day</title>
     <title>Privacy Policy</title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel="shortcut icon" href="images/favicon.ico" />
     <link rel="stylesheet" href="css/style.css">
     <script src="js/jquery.js"></script>
     <script src="js/jquery-migrate-1.1.1.js"></script>
     <script src="js/script.js"></script>
     <script src="js/superfish.js"></script>
     <script src="js/jquery.ui.totop.js"></script>
     <script src="js/jquery.equalheights.js"></script>
     <script src="js/jquery.mobilemenu.js"></script>
     <script src="js/jquery.easing.1.3.js"></script>
     <script src="js/jquery.horizontalNav.js"></script>
     <script>


      $(window).load(function() {
      $('.full-width').horizontalNav({});
     });

    $(document).ready(function(){
      $().UItoTop({ easingType: 'easeOutQuart' });
    });

    $(window).load(function() {
      $( ".lang" ).click(function() {
        $( ".drop" ).slideToggle( "slow" );
      });
    });
     </script>


<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "DuelAllDay" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>

    <div class="container_12">

    <div class="grid_12">
  <h1>
          <a href="index.html">
            <a href="http://tinypic.com?ref=wleo3k" target="_blank"><img src="http://i58.tinypic.com/wleo3k.png" border="0" alt="Image and video hosting by TinyPic"></a>
          </a>
        </h1>
        <div class="info">
          24/7 support  <span class="col1">1 800 345 67 89</span><a href="#">live chat</a><div class="lang">En <ul class="drop">
              <li class="current"><a href="#">English</a></li>
              <li><a href="#">Français</a> </li>
              <li><a href="#">Español</a> </li>
              <li><a href="#">Deutsch </a></li>

          </ul></div>
        </div>
        <div class="clear"></div>
      <div class="menu_block mb0">

          <nav class="horizontal-nav full-width horizontalNav-notprocessed">
              <ul class="sf-menu">
                     <li><a href="index.html">main</a></li>
                     <li><a href="index-1.html">download casino </a></li>
                     <li class="current"><a href="index-2.html">games </a>
                     <ul>
                          <li><a href="#">card games</a></li>
                          <li><a href="#">video slots</a></li>
                          <li><a href="#">roulette</a></li>
                       </ul>
                     </li>
                     <li><a href="index-3.html">banking</a></li>
                     <li><a href="index-4.html">tournaments</a></li>
                     <li><a href="index-5.html">contacts</a></li>
                   </ul>
                </nav>

              <div class="clear"></div>
    </div>

      </div>
    </div>
      <%= render 'layouts/navigation' %>


    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

  <div class="top_block"><div class="cash">
    <div class="container_12">

      <div class="grid_7 prefix_5">
        <div class="title">100% BONUS UP TO <div class="col1">$1000</div></div>
        <span class="tt"><span class="span col1">STEP 1</span> <span class="col2">DOWNLOAD AND INSTALL</span>(ADIPISCINRIS VEL TORTOR)</span>
        <span class="tt"><span class="span col1">STEP 2</span> <span class="col2">REGISTER</span>(ELIT MAURIS VEL  MENTUM AUCTOR)</span>
        <span class="tt"><span class="span col1">STEP 3</span> <span class="col2">DEPOSIT AND RECEIVE YOUR 100% BONUS</span>(VITAE NIBH COND)</span>
        <a href="#" class="btn">download now</a>
       </div>
      </div>
    </div>
  </div>

<div class="content">
  <div class="container_12">
    <div class="grid_8">
      <h3>Most Popular Casino Games</h3>
      <div class="game">
        <div class="box fl">
          <a href="http://tinypic.com?ref=2ecj478" target="_blank"><img src="http://i61.tinypic.com/2ecj478.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
          <a href="#">Praesent Vestibulum Molestie</a>
          <div class="stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span class="gray"></span>
          </div>
        </div>
        <div class="extra_wrapper">
          <div class="text1"><a href="#">Praesent Vestibulum Molestie</a></div>Nam aliquam pretium feugiat. Duis sem est, viverra eu interdum ac, suscipit nec mauris. Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellent
          <br>
          <a href="#" class="btn">play now!</a>
          <a href="#" class="btn">read rules</a>
        </div>
      </div>
      <div class="game">
        <div class="box fl">
          <a href="http://tinypic.com?ref=64gncj" target="_blank"><img src="http://i58.tinypic.com/64gncj.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
          <a href="#">Etiam Cursus Leo Vel Metus</a>
          <div class="stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span class="gray"></span>
          </div>
        </div>
        <div class="extra_wrapper">
          <div class="text1"><a href="#">Etiam Cursus Leo Vel Metus</a></div>Nam aliquam pretium feugiat. Duis sem est, viverra eu interdum ac, suscipit nec mauris. Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellent
          <br>
          <a href="#" class="btn">play now!</a>
          <a href="#" class="btn">read rules</a>
        </div>
      </div>
      <div class="game">
        <div class="box fl">
          <a href="http://tinypic.com?ref=21c5u39" target="_blank"><img src="http://i57.tinypic.com/21c5u39.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
          <a href="#">Vestibulum Ante Ipsum Primis</a>
          <div class="stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span class="gray"></span>
          </div>
        </div>
        <div class="extra_wrapper">
          <div class="text1"><a href="#">Vestibulum Ante Ipsum Primis</a></div>Nam aliquam pretium feugiat. Duis sem est, viverra eu interdum ac, suscipit nec mauris. Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellent
          <br>
          <a href="#" class="btn">play now!</a>
          <a href="#" class="btn">read rules</a>
        </div>
      </div>
      <div class="game">
        <div class="box fl">
          <a href="http://tinypic.com?ref=2qir3fc" target="_blank"><img src="http://i58.tinypic.com/2qir3fc.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
          <a href="#">Ultrices Posuere Cubilia Curae</a>
          <div class="stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span class="gray"></span>
          </div>
        </div>
        <div class="extra_wrapper">
          <div class="text1"><a href="#">Ultrices Posuere Cubilia Curae</a></div>Nam aliquam pretium feugiat. Duis sem est, viverra eu interdum ac, suscipit nec mauris. Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellent
          <br>
          <a href="#" class="btn">play now!</a>
          <a href="#" class="btn">read rules</a>
        </div>
      </div>
      <div class="game">
        <div class="box fl">
          <a href="http://tinypic.com?ref=wrgefd" target="_blank"><img src="http://i60.tinypic.com/wrgefd.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
          <a href="#">Donec Porta Diam Eu Massa</a>
          <div class="stars">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span class="gray"></span>
          </div>
        </div>
        <div class="extra_wrapper">
          <div class="text1"><a href="#">Donec Porta Diam Eu Massa</a></div>Nam aliquam pretium feugiat. Duis sem est, viverra eu interdum ac, suscipit nec mauris. Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellent
          <br>
          <a href="#" class="btn">play now!</a>
          <a href="#" class="btn">read rules</a>
        </div>
      </div>
    </div>
    <div class="grid_4 ">
    <div class="down">
      <h3 class="col1">How to Get Started</h3>
      <ul>
        <li><a href="#">download the casino</a></li>
        <li><a href="#">signup for real money play</a></li>
        <li><a href="#">deposit and collect your bonus!</a></li>
      </ul>
      <h3 class="col1">100% up to $1,000</h3>
      <a href="#">Download Casino <span>$ 777 welcome bonus!</span></a>
      </div>
      <h3>Big Cash Prizes!</h3>
      <div class="text1">Play in any of our weekly guaranteed
tournaments and you could win up to
$1,500 cash!</div>That’s not all, participate in our massive monthly
tournament and you will have a chance to win big!
      <div class="col1 un"><a href="#" class="link1">View the Tournament Calendar.</a></div>
      <h3>Need Help?</h3>
      <div class="text1">
        If you need help getting starting please
contact our <span class="col1"><a href="#">customer support</a></span> or you can
read our <span class="col1"><a href="#">Frequently asked questions </a></span>
      </div>
      <a href="#" class="inst">
        Instant Play
        <span>no download required</span>
      </a>
      <p></p>
      <center><h2>Live Chat</h2></center>
      <p></p>
      <script type="text/javascript" src="http://www3.smartchatbox.com/shoutbox/start.php?key=752186135"></script>

    </div>
  </div>
</div>

</body>
</html>

<footer>
  <div class="container_12">
    <div class="grid_12">
    <ul>
      <li><strong><a href="#">About Us</a></strong></li>
      <li><strong><a href="#">Responsible </a></strong></li>
      <li><strong><a href="#">Gaming </a></strong></li>
      <li><strong><a href="#">Security &amp; Privacy</a></strong></li>
      <li><strong><a href="#">Fair Play </a></strong></li>
      <li><strong><a href="#">User Agreement</a></strong></li>
      <li><strong><a href="#">Affiliates</a></strong></li>
      <li><strong><a href="#">News</a></strong></li>
      <li><strong><a href="#">Help</a></strong></li>
      <li><strong><a href="#">Site Map</a></strong></li>
    </ul>
    <p>Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec,
luctus a, lorem. Maecenas tristique orci ac sem. </p>
    <div class="pay">
      <a href="http://tinypic.com?ref=4h2x76" target="_blank"><img src="http://i62.tinypic.com/4h2x76.png" border="0" alt="Image and video hosting by TinyPic"></a>
      <a href="http://tinypic.com?ref=35902h1" target="_blank"><img src="http://i62.tinypic.com/35902h1.png" border="0" alt="Image and video hosting by TinyPic"></a>
      <a href="http://tinypic.com?ref=11ujf4k" target="_blank"><img src="http://i59.tinypic.com/11ujf4k.png" border="0" alt="Image and video hosting by TinyPic"></a>
      <a href="http://tinypic.com?ref=2dhcpoo" target="_blank"><img src="http://i61.tinypic.com/2dhcpoo.png" border="0" alt="Image and video hosting by TinyPic"></a>
    </div>
    <div class="copy">
     JackpotCity &copy; 2013 / <a href="index-6.html">Privacy policy</a></div>

    </div>
  </div>

</footer>
</body>
</html>

app/views/pages/Live Chat.html.erb
<head>
  Chat Now
</head>

<embed wmode="transparent" src="http://www.xatech.com/web_gear/chat/chat.swf" quality="high" width="540" height="405" name="chat" FlashVars="id=210905509" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://xat.com/update_flash.php" /><br><small><a target="_BLANK" href="http://xat.com/web_gear/?cb">Get your own Chat Box!</a> <a target="_BLANK" href="http://xat.com/web_gear/chat/go_large.php?id=210905509">Go Large!</a></small><br>

app/views/pages/home.html.erb
</head>

<body class="" id="top">
<header>
<div class="container_12">

<div class="grid_12">
<h1>
      <a href="index.html">
        <img src="images/logo.png" alt="Your Happy Family">
      </a>
      </ul></div>
    </div>
    <div class="clear"></div>
  <div class="menu_block">